name = "Create and Irons"
author = "ClassicSlime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98934f8f63fdf2ae9b649a0918938f6da0b52234dc3fec7146c3c204b5fe06d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
