name = "Create and Irons"
author = "ClassicSlime"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82823212cd2428a0d7157141391c580ce75bd66293c55dd79aa1cf44ed4c1cd4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
